apiVersion: v1
kind: Service
metadata:
  name: golocal-guide-service
spec:
  selector:
    app: golocal-guide
  ports:
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
