name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Minikube's Docker daemon
        run: |
          echo "Using Minikube Docker daemon..."
          eval $(minikube docker-env)

      - name: Build Docker image
        run: |
          docker build -t waleed2215/golocal-guide .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: docker push waleed2215/scdplozekt:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
